name: 'Cache dependencies'
description: 'Cache dependencies to speed up workflow runs'
runs:
    using: composite
    steps:
        - name: Restore cached node_modules
          id: cache
          uses: actions/cache@v4
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                  ${{ runner.os }}-deps-

        - name: Install dependencies
          shell: bash
          if: steps.cache.outputs.cache-hit != 'true'
          run: yarn install --frozen-lockfile --immutable --prefer-offline
