name: 'Restore build artifact'
description: 'Download artifact'
inputs:
    artifact-name:
        description: 'Name of the artifact'
        required: true
runs:
    using: composite
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Display structure of downloaded files
          shell: bash
          run: ls -R

        - uses: actions/download-artifact@v4
          with:
              name: ${{ inputs.artifact-name }}

        - name: Display structure of downloaded files
          shell: bash
          run: ls -R
