on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - '.github/workflows/main.yml'
            - 'lib/**'
            - 'test/**'
name: Main

env:
    DOCKER_IMAGE_TAG: ${{ github.event.repository.name }}/${{ github.ref_name }}:latest

jobs:
    install_deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile --immutable

            - name: Archive node_modules
              uses: actions/upload-artifact@v4
              with:
                  name: node_modules
                  path: node_modules
                  retention-days: 1
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Download node_modules
              uses: actions/download-artifact@v4
              with:
                  name: node_modules

            - name: Build Project
              run: yarn run build

    test:
        runs-on: ubuntu-latest
        needs: [install_deps]
        steps:
            - name: Download node_modules
              uses: actions/download-artifact@v4
              with:
                  name: node_modules

            - name: Lint Project
              run: yarn run lint:report

            - name: Run unit tests
              run: yarn run test:coverage

            - name: Archive testing report results
              uses: actions/upload-artifact@v4
              with:
                  name: test-report
                  path: test-report.xml
                  retention-days: 1

            - name: Run e2e
              run: yarn run test:e2e

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
