on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - '.github/**'
            - 'lib/**'
            - 'test/**'
name: Main

env:
    DOCKER_IMAGE_TAG: ${{ github.event.repository.name }}/${{ github.ref_name }}:latest

jobs:
    install_deps:
        name: 'Install dependencies'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: 'yarn.lock'

            - name: Restore cached node_modules
              id: yarn-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile --immutable --prefer-offline

    build:
        name: 'Build library'
        runs-on: ubuntu-latest
        needs: [install_deps]
        steps:
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      lib
                      package.json
                      tsconfig.build.json
                      tsconfig.json
                      yarn.lock

            - name: Set up Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: 'yarn.lock'

            - name: Restore cached node_modules
              id: yarn-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile --immutable --prefer-offline

            - name: Build
              run: yarn run build

    test:
        name: 'Testing, linting and Quality check'
        runs-on: ubuntu-latest
        needs: [install_deps]
        steps:
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      lib
                      test
                      package.json
                      tsconfig.build.json
                      tsconfig.json
                      yarn.lock

            - name: Set up Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: 'yarn.lock'

            - name: Restore cached node_modules
              id: yarn-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile --immutable --prefer-offline

            - name: Lint Project
              run: yarn run lint:report

            - name: Run unit tests
              run: yarn run test:coverage

            - name: Archive testing report results
              uses: actions/upload-artifact@v4
              with:
                  name: test-report
                  path: test-report.xml
                  retention-days: 0

            - name: Run e2e
              run: yarn run test:e2e

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
